- Name: "Verbit"
  Description: ""
  Website: "https://verbit.ai/"
  Alternatives: []
- Name: "TimeOS"
  Description: ""
  Website: "https://timeos.ai/"
  Alternatives: []
- Name: "SysAid Technologies"
  Description: ""
  Website: "https://sysaid.com/"
  Alternatives: []
- Name: "Rupert"
  Description: ""
  Website: "https://hirupert.co/"
  Alternatives: []
- Name: "Powtoon"
  Description: ""
  Website: "https://powtoon.com/"
  Alternatives: []
- Name: "Monday.com"
  Description: ""
  Website: "https://monday.com/"
  Alternatives: []
- Name: "Komodor"
  Description: ""
  Website: "https://komodor.com/"
  Alternatives: []
- Name: "Lightico"
  Description: ""
  Website: "https://lightico.com/"
  Alternatives: []
- Name: "Kryon Systems"
  Description: ""
  Website: "http://kryonsystems.com/"
  Alternatives: []
- Name: "Honeybook"
  Description: ""
  Website: "https://honeybook.com/"
  Alternatives: []
- Name: "Groove"
  Description: ""
  Website: "https://groove.ooo/"
  Alternatives: []
- Name: "Fiverr"
  Description: ""
  Website: "https://fiverr.com/"
  Alternatives: []
- Name: "Connecteam"
  Description: ""
  Website: "https://connecteam.com/"
  Alternatives: []
- Name: "Bizzabo"
  Description: ""
  Website: "https://bizzabo.com/"
  Alternatives: []
- Name: "Kape Technologies, previously known as Crossrider"
  Description: "-UK-based company cofounded by an ex-Israeli surveillance agent and a billionaire previously convicted of insider trading who was later named in the Panama Papers. -Source: https://shorturl.at/eGW49 -Brands: ExpressVPN, Private Internet Access, CyberGhost VPN, ZenMate VPN, Intego Antivirus, Webselenese"
  Website: "https://www.kape.com/"
  Alternatives:
    - Name: "Proton"
      Description: "Proton Mail, VPN, Pass, Drive"
      Website: "https://proton.me/"
